#!/usr/bin/env bash
# Regenerate every app icon from art/icon-master.png, then strip the alpha channel from the iOS set.
#
# Why the second step: `tauri icon` always writes the iOS AppIcon PNGs as RGBA, and App Store Connect
# REJECTS the 1024x1024 marketing icon if it carries an alpha channel ("can't be transparent nor
# contain an alpha channel") — the upload fails, not the build. Our art is fully opaque (alpha is 255
# everywhere), so dropping the channel is lossless.
#
# `src-tauri/gen/` is gitignored and regenerated by `tauri ios init`, so re-run this after any regen.
set -euo pipefail

cd "$(dirname "$0")/.."

MASTER="art/icon-master.png"
APPICONSET="src-tauri/gen/apple/Assets.xcassets/AppIcon.appiconset"

[ -f "${MASTER}" ] || { echo "✖ Missing ${MASTER}"; exit 1; }

echo "▶ Generating icons from ${MASTER}…"
pnpm tauri icon "${MASTER}"

if [ -d "${APPICONSET}" ]; then
  echo "▶ Stripping alpha from the iOS AppIcon set…"
  python3 - "${APPICONSET}" <<'PY'
import sys, glob, os
from PIL import Image

stripped = 0
for path in sorted(glob.glob(os.path.join(sys.argv[1], "*.png"))):
    im = Image.open(path)
    if im.mode == "RGB":
        continue
    alpha = im.convert("RGBA").getchannel("A").getextrema()
    if alpha != (255, 255):
        print(f"  ! {os.path.basename(path)} has REAL transparency {alpha} — flattening onto black")
    Image.alpha_composite(
        Image.new("RGBA", im.size, (0, 0, 0, 255)), im.convert("RGBA")
    ).convert("RGB").save(path, "PNG")
    stripped += 1
print(f"  stripped alpha from {stripped} icon(s)")
PY
else
  echo "  (no ${APPICONSET} — run 'pnpm tauri ios init' first if you need iOS icons)"
fi

# `tauri icon` always emits an Android set. This app targets macOS/Windows desktop + iOS only
# (see docs/specs/rimokon-miru.md §8), so drop it rather than carry a misleading empty platform.
if [ -d "src-tauri/icons/android" ]; then
  rm -rf src-tauri/icons/android
  echo "▶ Removed the Android icon set (not a target platform)."
fi

echo "✅ Icons regenerated."
